### ISSUE TITLE
question - is this cross platform?

### ISSUE THREAD

**Issue by avnerbarr** [knsd/daemonize#43] opened 2020-09-29 12:40 UTC
will it run on windows/linux/mac? 
thanks

**Comment by Alexhuszagh** [comment] 2021-04-05 15:41
It can't be: it extensively uses `std::os::unix` in its imports, which seems to be preventing this from working.

**Comment by eun-ice** [comment] 2021-04-05 16:09
I can confirm daemonize to work flawlessly on mac and linux.

**Comment by Alexhuszagh** [comment] 2021-04-05 16:45
> I can confirm daemonize to work flawlessly on mac and linux.

Definitely, it just extensively uses Unix functionality, which isn't supported on Windows. So it will support all Unix-like systems very robustly, just not sure how you'd implement this on Windows.

**Comment by knsd** [comment] 2021-07-27 07:39
This library aims to support any Unix system, Windows support is out of scope for now.

**Closed by knsd** 2021-07-27 07:39 UTC
